=== jmerlop327/lenguajes_daw/u03/DTD/boletin03/XSD/PruebaRegex.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="prueba_regex">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="valor" maxOccurs="unbounded">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="([A-Z][a-z])*[A-Z]?"/>
                        <xs:maxLength value="10"/>
                        <xs:minLength value="3"/>
                    </xs:restriction>
                </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== jmerlop327/lenguajes_daw/u03/DTD/boletin03/XSD/PruebaRegex.xml
<?xml version="1.0" encoding="UTF-8"?>
<prueba_regex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="./PruebaRegex.xsd">
<!-- TANTOS VALORES COMO QUERAMOS PROBAR -->
<valor>AbCdEfGhIjK</valor>
<valor>AbCdEf</valor>
<valor>HoLa</valor>
<valor>AdIoS</valor>
<valor>A</valor>
<valor>AyO</valor>
<valor>ArAAf</valor>
</prueba_regex>
