<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE musicos [
  <!ELEMENT musicos (musico*)>
  <!ELEMENT musico ((nombre | apodo), fechaNacimiento)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT apodo (#PCDATA)>
  <!ELEMENT fechaNacimiento (#PCDATA)>
]>
<musico>
  <nombre>Antonio Vivaldi</nombre>
  <apodo>El cura pelirrojillo</apodo>
  <fechaNacimiento>04/03/1678</fechaNacimiento>
</musico>
<musico>
  <nombre>Johann Sebastian Bach</nombre>
  <apodo>El viejo peluca</apodo>
  <fechaNacimiento>21 de marzo de 1685</fechaNacimiento>
</musico>
